#!/usr/bin/env python3
"""
Convert logo PNG to base64 data URL for PDFMake
Handles transparency by flattening to white background (PDFMake doesn't support alpha)
Calculates proper aspect ratio for PDF dimensions

Usage: python tools/convert-logo-to-base64.py
Output: assets/js/logo-data.js
"""

import base64
import sys
from pathlib import Path
from datetime import datetime

try:
    from PIL import Image
except ImportError:
    print("ERROR: PIL/Pillow is required. Install with: pip install Pillow")
    sys.exit(1)


def convert_image_to_base64(source_path, output_js_path, target_width=80):
    """
    Convert PNG image to JPEG base64 data URL for PDFMake
    - Converts to JPEG to avoid alpha channel issues (PDFMake doesn't support PNG transparency well)
    - Flattens transparency to white background
    - Calculates proper height to maintain aspect ratio
    """
    try:
        print(f"Loading image: {source_path}")
        img = Image.open(source_path)

        original_width, original_height = img.size
        original_mode = img.mode
        print(f"  Original: {original_width}x{original_height}, Mode: {original_mode}")

        # Calculate aspect ratio and target height
        aspect_ratio = original_width / original_height
        target_height = round(target_width / aspect_ratio)
        print(f"  Target PDF size: {target_width}x{target_height} (aspect ratio: {aspect_ratio:.3f})")

        # Handle transparency - flatten to white background
        if img.mode == 'RGBA':
            print("  Flattening transparency to white background...")
            background = Image.new('RGB', img.size, (255, 255, 255))
            background.paste(img, mask=img.split()[3])  # Use alpha channel as mask
            img = background
        elif img.mode != 'RGB':
            print(f"  Converting {img.mode} to RGB...")
            img = img.convert('RGB')

        # Save to bytes as JPEG (no alpha channel, solves PDFMake black background issue)
        from io import BytesIO
        buffer = BytesIO()
        img.save(buffer, format='JPEG', quality=95, optimize=True)
        image_data = buffer.getvalue()

        # Also save the JPEG version as a file for reference
        jpeg_path = source_path.parent / 'FVU-logo-white-bg.jpg'
        img.save(jpeg_path, 'JPEG', quality=95, optimize=True)
        print(f"  Saved JPEG version: {jpeg_path.name}")

        # Encode to base64
        print("  Encoding to base64...")
        base64_data = base64.b64encode(image_data).decode('utf-8')
        data_url = f'data:image/jpeg;base64,{base64_data}'

        # Create JavaScript module
        js_content = f'''/**
 * FVU Logo Data
 * Auto-generated base64 data URL for PDFMake
 * Source: {source_path.name} (converted to JPEG with white background)
 * Original: {original_width}x{original_height} pixels, {original_mode} mode
 * Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}
 *
 * Note: Using JPEG format to avoid PDFMake black background issues with PNG transparency
 * To regenerate: python tools/convert-logo-to-base64.py
 *
 * DO NOT EDIT THIS FILE MANUALLY
 */

export const FVU_LOGO_BASE64 = '{data_url}';

// Logo dimensions for PDF (maintains aspect ratio)
// Original: {original_width}x{original_height}, Aspect ratio: {aspect_ratio:.3f}
export const FVU_LOGO_WIDTH = {target_width};
export const FVU_LOGO_HEIGHT = {target_height};

/**
 * Validate logo data URL format
 * @returns {{{{valid: boolean, message: string}}}} Validation result
 */
export function validateLogoData() {{
  if (!FVU_LOGO_BASE64.startsWith('data:image/png;base64,') && !FVU_LOGO_BASE64.startsWith('data:image/jpeg;base64,')) {{
    return {{ valid: false, message: 'Invalid logo data URL format' }};
  }}
  if (FVU_LOGO_BASE64.length < 1000) {{
    return {{ valid: false, message: 'Logo data URL seems too short' }};
  }}
  try {{
    const base64String = FVU_LOGO_BASE64.split(',')[1];
    atob(base64String.substring(0, 100));
    return {{ valid: true, message: 'Logo data is valid' }};
  }} catch (error) {{
    return {{ valid: false, message: `Logo base64 corrupted: ${{error.message}}` }};
  }}
}}
'''

        # Write to output file
        print(f"  Writing: {output_js_path}")
        output_js_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_js_path, 'w', encoding='utf-8') as f:
            f.write(js_content)

        # Print summary
        print(f"\n{'='*60}")
        print("SUCCESS!")
        print(f"{'='*60}")
        print(f"  Source:        {source_path.name}")
        print(f"  Output:        {output_js_path.name}")
        print(f"  Original mode: {original_mode} -> JPEG (white background)")
        print(f"  Format:        JPEG (no alpha channel, fixes PDFMake black bg)")
        print(f"  File size:     {len(image_data):,} bytes ({len(image_data)/1024:.1f} KB)")
        print(f"  Base64 size:   {len(base64_data):,} chars ({len(base64_data)/1024:.1f} KB)")
        print(f"  PDF dimensions: {target_width}x{target_height}px")
        print(f"{'='*60}\n")

        return True

    except FileNotFoundError:
        print(f"ERROR: File not found: {source_path}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    project_root = Path(__file__).parent.parent
    source_path = project_root / 'assets' / 'images' / 'FVU logo.PNG'
    output_path = project_root / 'assets' / 'js' / 'logo-data.js'

    convert_image_to_base64(source_path, output_path)
