#!/usr/bin/env python3
"""
Convert logo PNG to base64 data URL for PDFMake
Usage: python tools/convert-logo-to-base64.py
Output: assets/js/logo-data.js
"""

import base64
import sys
from pathlib import Path
from datetime import datetime

def convert_image_to_base64(image_path, output_path):
    """Convert PNG image to base64 data URL and write to JS module"""

    try:
        # Read image file
        print(f"Reading image from: {image_path}")
        with open(image_path, 'rb') as img_file:
            image_data = img_file.read()

        # Encode to base64
        print("Encoding to base64...")
        base64_data = base64.b64encode(image_data).decode('utf-8')

        # Create data URL
        data_url = f'data:image/png;base64,{base64_data}'

        # Create JavaScript module
        js_content = f'''/**
 * FVU Logo Data
 * Auto-generated base64 data URL for PDFMake
 * Source: {image_path.name}
 * Generated: {datetime.now().isoformat()}
 *
 * To regenerate: python tools/convert-logo-to-base64.py
 *
 * DO NOT EDIT THIS FILE MANUALLY
 * This file is auto-generated from the PNG source
 */

export const FVU_LOGO_BASE64 = '{data_url}';

// Logo dimensions (for reference)
export const FVU_LOGO_WIDTH = 80;
export const FVU_LOGO_HEIGHT = 80;

/**
 * Validate logo data URL format
 * @returns {{valid: boolean, message: string}} Validation result
 */
export function validateLogoData() {{
  // Check if it's a valid data URL
  if (!FVU_LOGO_BASE64.startsWith('data:image/png;base64,')) {{
    return {{ valid: false, message: 'Invalid logo data URL format' }};
  }}

  // Check minimum length (1x1 PNG is ~90 chars, real logo should be much larger)
  if (FVU_LOGO_BASE64.length < 1000) {{
    return {{ valid: false, message: 'Logo data URL seems too short - may be placeholder' }};
  }}

  // Try to decode base64 (basic validation)
  try {{
    const base64String = FVU_LOGO_BASE64.split(',')[1];
    atob(base64String.substring(0, 100)); // Test decode first 100 chars
    return {{ valid: true, message: 'Logo data is valid' }};
  }} catch (error) {{
    return {{ valid: false, message: `Logo base64 data is corrupted: ${{error.message}}` }};
  }}
}}
'''

        # Write to output file
        print(f"Writing output to: {output_path}")
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, 'w', encoding='utf-8') as js_file:
            js_file.write(js_content)

        print(f"\n{'='*60}")
        print("SUCCESS: Logo converted successfully!")
        print(f"{'='*60}")
        print(f"  Source:       {image_path}")
        print(f"  Output:       {output_path}")
        print(f"  Original size: {len(image_data):,} bytes ({len(image_data)/1024:.1f} KB)")
        print(f"  Base64 size:   {len(base64_data):,} characters")
        print(f"  Data URL size: {len(data_url):,} characters ({len(data_url)/1024:.1f} KB)")
        print(f"{'='*60}\n")

        # Validate PNG signature
        if image_data[:4] == b'\x89PNG':
            print("VALID: PNG signature validated")
        else:
            print("WARNING: PNG signature not found - file may be corrupted")

        return True

    except FileNotFoundError:
        print(f"ERROR: Image file not found: {image_path}", file=sys.stderr)
        sys.exit(1)
    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

if __name__ == '__main__':
    # Paths
    project_root = Path(__file__).parent.parent
    image_path = project_root / 'assets' / 'images' / 'FVU logo.PNG'
    output_path = project_root / 'assets' / 'js' / 'logo-data.js'

    convert_image_to_base64(image_path, output_path)
